### ISSUE TITLE
Typos and comments on README.md

### ISSUE THREAD

**Issue by powerjg** [spwilson2/whimsy#2]
This is really great! Just some small comments/typos, really. 

- In overview or somewhere towards the top, can you define suite, fixture, etc. I doubt most of the community will know what these words mean. Linking to a wiki page would probably be enough.
 - Under "Test Running Step" the following is confusing: 
> The Runner first sets up any Fixture objects that are not lazy_init. Once all these lazy_init fixtures have been set up the Runner begins to iterate through its suites.
 - Can you give an example of why a test would have fail_fast set? Maybe building?
 - "as tests are ran" -> "as tests are run"
 - ellided -> elided
 - How do I find out what are the currently implemented verifiers, fixtures, etc? Can we generate the docs automatically or something?
 - In section "Running your test": what happens if the test is in gem5/tests?
  - Does the uid include the full path? How do you compare between systems (e.g., my computer and yours)?
    - Do you have to use the full path when running?
    - Maybe the example would be better if using gem5/tests?
 - `elif e.returncode != 2:` -> `elif e.returncode == 2:`?
 - DisckGeneratorFixture -> DiskGeneratorFixture
 - The disk generator fixture is a good example! It is possible, though not very useful for gem5 to use an empty binary blob. Though, you could imagine also formatting the disk in the fixture :).

**Comment by spwilson2** [comment]
## Additional notes to myself 

(You brought this up and I had thought it but forgot to make change) UID's should take the path relative to the `base_dir` (so they will be common for all users).

Also something you basically said: All my examples should consistently fit into the gem5 repo rather than crisscrossing between the two.

**Comment by powerjg** [comment]
Is the following correct?

All tests are assumed to be of the form:
<some gem5 binary> <some config file>.py (optionally, <some other options>)

I guess this makes sense. It's similar to what we currently have, correct?

Assuming I understand things, I think this should be made clear in the README

**Comment by spwilson2** [comment]
(I think all issues have been fixed and another lookthrough was made with #8 )

**Comment by powerjg** [comment]
Agreed. It looks great!

Jason
