### ISSUE TITLE
Test discovery names

### ISSUE THREAD

**Issue by powerjg** [spwilson2/whimsy#3]
Maybe we should be less stringent on the filenames for test discovery. What do you think of also including if the directory name has "test" in it. For instance: 
ruby-tests/
     MI-example.py 
     MOESI-hammer.py

**Comment by spwilson2** [comment]
I could go both ways on this - my argument against it is that we might want to have configs in the same directory as tests. It also might be confusing at first if only files specifically in a directory name sample-tests were collected but not a sub-directory. But, either way works I don't have a strong preference.

- sample-tests/
  - MI-example.py
  - configs/
    - MOESI-hammer.py

MOESI-hammer.py could end up being a confusing edge case to users in the above.

**Comment by powerjg** [comment]
I see what you're saying. I didn't think that far ahead.

Basically the "*test*.py" would be the test file that has the test description in it. All other python files would be gem5 config files or gem5 runscripts.

I get it now! I really like this!

Can you make this more clear in the README?

**Comment by spwilson2** [comment]
Will do, thanks for the feedback!
