### ISSUE TITLE
Thoughts on different gem5 binaries

### ISSUE THREAD

**Issue by powerjg** [spwilson2/whimsy#4]
It's important to make sure that all of the different binaries build (e.g., opt, fast, etc), but really only .opt needs to execute tests.

Note: We don't want to use .fast to execute tests because it elides panics, etc.

**Comment by spwilson2** [comment]
One reason I would really argue that we test fast is for exactly that reason. I know I have made the mistake of putting code that is critical/had side effects in an assert statement (and had it compiled out).

**Comment by powerjg** [comment]
Sure, there's a good argument for running fast. Probably now debug, prof, and perf, though.

**Comment by spwilson2** [comment]
Note to myself: Still keep those tags as options, just make sure not to include them in quick tags. (Make a note in the readme for how users can do this)
