### ISSUE TITLE
How to understand the code?

### ISSUE THREAD

**Issue by powerjg** [spwilson2/whimsy#6]
You had a bit about this in the README.md, but maybe it would be a good idea to put a README.md in whimsy/ so when I'm looking at the code I know what I'm looking at. I think a little general thing about "here's what each file has" and "this is where main() is" would be very helpful. You could move what you have in the other README about __new__ in here.

**Comment by spwilson2** [comment]
Added a FILES.md in `whimsy/` I'll also be sure to add a more detailed description in each (module's docstring if there isn't a decent one already) before closing this issue.

**Comment by spwilson2** [comment]
I also realized that sphinx doesn't like it when modules run code on import, so I will need to refactor a bit  before I can add a description on how to build html documentation. (I'll do that as a last minute thing since I don't see that as super high priority atm.)
